name: Code Review with OpenAI
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: "Pull Request Number"
        required: true

permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: freeedcom/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
          OPENAI_API_MODEL: "gpt-4o"
          exclude: "yarn.lock,dist/**"
          PULL_REQUEST_NUMBER: ${{ github.event.inputs.pull_request_number }}
